language: php

cache:
    directories:
        - vendor

matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 7.3
          env: CONFIG="phpunit.xml" COVERGAGE="unit"
        - php: 7.3
          env: CONFIG="phpunit-integration-legacy.xml" COVERGAGE="integration"
        - php: 7.4
          env: CONFIG="phpunit.xml" COVERGAGE="unit"
        - php: 7.4
          env: CONFIG="phpunit-integration-legacy.xml" COVERGAGE="integration"

# test only master (+ pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/
        - /^\d.\d+-release$/

# make sure to update composer to latest available version
before_install:
    - ./tests/configure_dependencies.sh
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# install dependencies
install:
    - travis_wait composer install

# execute phpunit as the script command
script:
    - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c $CONFIG --coverage-clover=coverage.xml

# disable mail notifications
notification:
    email: false

# reduce depth (history) of git checkout
git:
    depth: 30

# we don't need sudo
sudo: false

# send coverage to codecov.io
after_success:
    - bash <(curl -s https://codecov.io/bash) -F $COVERGAGE
