parameters:
    # Content view fallback templates
    netgen.ezplatform_site.content_view_fallback.to_ez_platform.embed: '@@NetgenEzPlatformSiteApi/content_view_fallback/to_ez_platform/embed.html.twig'
    netgen.ezplatform_site.content_view_fallback.to_ez_platform.view: '@@NetgenEzPlatformSiteApi/content_view_fallback/to_ez_platform/view.html.twig'
    netgen.ezplatform_site.content_view_fallback.to_site_api.embed: '@@NetgenEzPlatformSiteApi/content_view_fallback/to_site_api/embed.html.twig'
    netgen.ezplatform_site.content_view_fallback.to_site_api.view: '@@NetgenEzPlatformSiteApi/content_view_fallback/to_site_api/view.html.twig'
