services:
    netgen.ezplatform_site.twig.extension.field_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\FieldRenderingExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen.ezplatform_site.twig.runtime.field_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\FieldRenderingRuntime
        # public: false
        arguments:
            - '@twig'
            - '@ezpublish.templating.field_block_renderer'
            - '@ezpublish.fieldType.parameterProviderRegistry'
        tags:
            - {name: twig.runtime}

    netgen.ezplatform_site.twig.extension.image:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\ImageExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen.ezplatform_site.twig.runtime.image:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\ImageRuntime
        # public: false
        arguments:
            - '@ezpublish.fieldType.ezimage.variation_service'
        tags:
            - { name: twig.runtime }

    netgen.ezplatform_site.twig.extension.query:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\QueryExtension
        tags:
            - { name: twig.extension }
        public: false

    netgen.ezplatform_site.twig.runtime.query:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\QueryRuntime
        # public: false
        arguments:
            - '@netgen.ezplatform_site.query_type.query_executor'
        tags:
            - { name: twig.runtime }
