parameters:
    # Defaults for Site API bundle semantic configuration
    netgen_ez_platform_site_api.default.override_url_alias_view_action: false
    netgen_ez_platform_site_api.default.use_always_available_fallback: true
    netgen_ez_platform_site_api.default.fail_on_missing_fields: '%kernel.debug%'
    netgen_ez_platform_site_api.default.render_missing_field_info: false

    # Default view templates
    netgen.ezplatform_site.default_view_templates.content.asset_image: "@@NetgenEzPlatformSiteApi/default/content/asset_image.html.twig"
    netgen.ezplatform_site.default_view_templates.content.embed: "@@NetgenEzPlatformSiteApi/default/content/embed.html.twig"
    netgen.ezplatform_site.default_view_templates.content.embed_image: "@@NetgenEzPlatformSiteApi/default/content/embed_image.html.twig"
    netgen.ezplatform_site.default_view_templates.content.embed_inline: "@@NetgenEzPlatformSiteApi/default/content/embed_inline.html.twig"
    netgen.ezplatform_site.default_view_templates.content.full: "@@NetgenEzPlatformSiteApi/default/content/full.html.twig"
    netgen.ezplatform_site.default_view_templates.content.line: "@@NetgenEzPlatformSiteApi/default/content/line.html.twig"
    netgen.ezplatform_site.default_view_templates.content.text_linked: "@@NetgenEzPlatformSiteApi/default/content/text_linked.html.twig"
    # List of content type identifiers to display as image when embedded
    netgen.ezplatform_site.content_view.image_embed_content_type_identifiers: ['image']

    # Default eZ Platform settings
    # By default we don't override URL alias view action, for that reason this is commented out
    #ezsettings.default.pagelayout: '@@NetgenEzPlatformSiteApi/pagelayout.html.twig'

    ezsettings.default.ngcontent_view_defaults:
        asset_image:
            default:
                template: '%netgen.ezplatform_site.default_view_templates.content.asset_image%'
                match: []
        embed:
            image:
                template: '%netgen.ezplatform_site.default_view_templates.content.embed_image%'
                match:
                    Identifier\ContentType: '%netgen.ezplatform_site.content_view.image_embed_content_type_identifiers%'
            default:
                template: "%netgen.ezplatform_site.default_view_templates.content.embed%"
                match: []
        embed-inline:
            default:
                template: "%netgen.ezplatform_site.default_view_templates.content.embed_inline%"
                match: []
        # Default full view is intentionally disabled because for some cases we depend on Content
        # redirecting to the homepage when the full view is not configured.
        #full:
        #    default:
        #        template: "%netgen.ezplatform_site.default_view_templates.content.full%"
        #        match: []
        line:
            default:
                template: "%netgen.ezplatform_site.default_view_templates.content.line%"
                match: []
        text_linked:
            default:
                template: "%netgen.ezplatform_site.default_view_templates.content.text_linked%"
                match: []
