parameters:
    # Defaults for Site API bundle semantic configuration
    netgen_ez_platform_site_api.default.override_url_alias_view_action: false
    netgen_ez_platform_site_api.default.use_always_available_fallback: true
    netgen_ez_platform_site_api.default.fail_on_missing_fields: '%kernel.debug%'
    netgen_ez_platform_site_api.default.render_missing_field_info: false
    netgen_ez_platform_site_api.default.named_objects: []
