system:
    default:
        field_templates:
            - { template: "@NetgenEzPlatformSiteApi/content_fields.html.twig", priority: 0 }
        fielddefinition_settings_templates:
            - { template: "@NetgenEzPlatformSiteApi/field_definition_settings.html.twig", priority: 0 }
