imports:
    - { resource: services/*.yml }

services:
    netgen.ezplatform_site.controller.base:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Controller\Controller
        public: true
        abstract: true
        calls:
            - [setContainer, ['@service_container']]

    netgen.ezplatform_site.core.settings:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Core\Site\Settings
        public: false
        arguments:
            - '@ezpublish.config.resolver'

    netgen.ezplatform_site.controller.content.view:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Controller\Content\ViewController
        parent: ezpublish.controller.base
        public: true

    ng_content:
        alias: netgen.ezplatform_site.controller.content.view
        public: true

    netgen.ezplatform_site.param_converter.location:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Converter\ContentParamConverter
        arguments:
            - '@netgen.ezplatform_site.load_service'
        tags:
            - { name: request.param_converter, priority: -1 }

    netgen.ezplatform_site.param_converter.content:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Converter\LocationParamConverter
        arguments:
            - '@netgen.ezplatform_site.load_service'
        tags:
            - { name: request.param_converter, priority: -1 }
