imports:
    - { resource: services/templating.yml }

parameters:
    # Template defaults for standard eZ Platform installation
    # By default we don't override URL alias view action, for that reason these are commented out
    #ezplatform.default_view_templates.content.full: 'NetgenEzPlatformSiteApiBundle:default:content/full.html.twig'
    #ezsettings.default.pagelayout: 'NetgenEzPlatformSiteApiBundle::pagelayout.html.twig'

    # Defaults for semantic configuration
    netgen_ez_platform_site_api.default.override_url_alias_view_action: false
    netgen_ez_platform_site_api.default.use_always_available_fallback: true
    netgen_ez_platform_site_api.default.fail_on_missing_fields: '%kernel.debug%'
    netgen_ez_platform_site_api.default.render_missing_field_info: false

services:
    netgen.ezplatform_site.controller.base:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Controller\Controller
        public: true
        abstract: true
        calls:
            - [setContainer, ['@service_container']]

    netgen.ezplatform_site.core.settings:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Core\Site\Settings
        public: false
        arguments:
            - '@ezpublish.config.resolver'

    netgen.ezplatform_site.controller.content.view:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Controller\Content\ViewController
        parent: ezpublish.controller.base
        public: true

    ng_content:
        alias: netgen.ezplatform_site.controller.content.view
        public: true

    netgen.ezplatform_site.sort_clause_parser:
        class: Netgen\EzPlatformSiteApi\Core\Site\QueryType\SortClauseParser
        public: false

    netgen.ezplatform_site.query_type.parameter_processor:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\QueryType\ParameterProcessor
        arguments:
            - '@request_stack'
            - '@ezpublish.config.resolver'
        public: false

    netgen.ezplatform_site.query_type.query_definition_mapper:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\QueryType\QueryDefinitionMapper
        arguments:
            - '@ezpublish.query_type.registry'
            - '@netgen.ezplatform_site.query_type.parameter_processor'
            - '@ezpublish.config.resolver'
        public: false

    netgen.ezplatform_site.query_type.query_executor:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\QueryType\QueryExecutor
        arguments:
            - '@ezpublish.query_type.registry'
            - '@netgen.ezplatform_site.filter_service'
            - '@netgen.ezplatform_site.find_service'
        public: false

    netgen.ezplatform_site.routing.content_url_alias_router:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Routing\ContentUrlAliasRouter
        public: false
        arguments:
            - "@ezpublish.urlalias_generator"
            - "@?router.request_context"
        tags:
            - { name: router, priority: 200 }

    netgen.ezplatform_site.routing.location_url_alias_router:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Routing\LocationUrlAliasRouter
        public: false
        arguments:
            - "@ezpublish.urlalias_generator"
            - "@?router.request_context"
        tags:
            - { name: router, priority: 200 }

    netgen.ezplatform_site.param_converter.location:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Converter\ContentParamConverter
        arguments:
            - '@netgen.ezplatform_site.site'
        tags:
            - { name: request.param_converter, priority: -1 }

    netgen.ezplatform_site.param_converter.content:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Converter\LocationParamConverter
        arguments:
            - '@netgen.ezplatform_site.site'
        tags:
            - { name: request.param_converter, priority: -1 }
