parameters:
    ezsettings.default.ng_named_query: {}

services:
    netgen.ezplatform_site.view_builder.content:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\View\Builder\ContentViewBuilder
        public: false
        arguments:
            - '@netgen.ezplatform_site.site'
            - '@ezpublish.api.repository'
            - '@ezpublish.view.configurator'
            - '@ezpublish.view.view_parameters.injector.dispatcher'

    netgen.ezplatform_site.ngcontent_view_provider.configured:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\View\Provider\Configured
        arguments:
            - '@netgen.ezplatform_site.ngcontent_view.matcher_factory'
            - '@netgen.ezplatform_site.query_type.query_definition_mapper'
        tags:
            - { name: ezpublish.view_provider, type: 'Netgen\Bundle\EzPlatformSiteApiBundle\View\ContentView', priority: 110 }
        public: false

    netgen.ezplatform_site.ngcontent_view.matcher_factory:
        class: eZ\Bundle\EzPublishCoreBundle\Matcher\ServiceAwareMatcherFactory
        arguments:
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
        calls:
            - [setContainer, ["@service_container"]]
            - [setMatchConfig, [$ngcontent_view$]]
        public: false

    netgen.ezplatform_site.ngcontent_view_provider.default_configured:
        class: eZ\Bundle\EzPublishCoreBundle\View\Provider\Configured
        arguments:
            - '@netgen.ezplatform_site.ngcontent_view.default_matcher_factory'
        tags:
            - {name: ezpublish.view_provider, type: 'Netgen\Bundle\EzPlatformSiteApiBundle\View\ContentView', priority: 90}
        public: false

    netgen.ezplatform_site.ngcontent_view.default_matcher_factory:
        class: eZ\Bundle\EzPublishCoreBundle\Matcher\ServiceAwareMatcherFactory
        arguments:
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
        calls:
            - [setContainer, ["@service_container"]]
            - [setMatchConfig, [$content_view_defaults$]]
        public: false
